### ISSUE TITLE
wurst compile errors on importing TextTagEntity from frentity/entity/TextTagEntity

### ISSUE THREAD

**Issue by Krypt0n** [Frotty/Frentity#1]
getting serveral errors on importing TextTagEntity
see below:
![frentity_compile_error](https://user-images.githubusercontent.com/640169/41749564-6b3d1864-75b7-11e8-8f41-5f2155c74e24.PNG)

jenkins build seems also to be failed aswell: http://peeeq.de/hudson/job/Frentity/552/console

**Comment by Krypt0n** [comment]
fix is needed because of TerrainUtils has been updated ([link to commit](https://github.com/wurstscript/wurstStdlib2/commit/cd05b0a7e538b59eb05514563f28783467bc25a9#diff-7)):
replace in PhysicsEntity.wurst
   line 24: 	terrainZ = getTerrainZ(pos.x, pos.y)
      with:   	terrainZ = pos.getTerrainZ()

replace in Entity.wurst
 line 100: 	if pos.z > (DYNAMIC_Z ? getTerrainZ(pos.toVec2()) : 0)
      with:   	if pos.z > (DYNAMIC_Z ? pos.getTerrainZ() : 0)

... etc.

**Comment by Frotty** [comment]
Thanks for the report. The standard library update wasn't supposed to be a breaking change. 
I have pushed stdlib fixes and will update this repo soon.

**Comment by Krypt0n** [comment]
i also needed to rename the EventListener see this [commit](https://github.com/Krypt0n/Frentity/commit/3a12922fd446455397fa4e4cc1960e4f41b793bc)

**Comment by Frotty** [comment]
Oh, must have been a mistake then.
However yes, `Event` from Frentity will be moved to stdlib as `ClosureEvents` very soon (this month) with some additions.
Then I will also do some cleanup on Frentity.
Thanks for the feedback
