### ISSUE TITLE
Invalid image in Documentation.md

### ISSUE THREAD

**Issue by RectangleEquals** [Frotty/Frentity#10]
Right after "you can easily create the following effect," there appears to be a placeholder image which states "This content is not available". The text that comes afterward describes a different image, so I can only assume this is undesired?

**Comment by Frotty** [comment]
Seems like the gif was removed. It was something similar to this:
![2018-01-17_02-26-08](https://user-images.githubusercontent.com/1486037/75614446-13b34280-5b39-11ea-9acc-ed77d5bee971.gif)

**Comment by Frotty** [comment]
I replaced the image
