### ISSUE TITLE
 Which wc3 version can use  

### ISSUE THREAD

**Issue by HarounGY** [Frotty/Frentity#5]
hi， Frotty
I need your help 
my wc3 version is 1.27a  
can not load the map

**Comment by Frotty** [comment]
Are you sure this library is the issue? 
I think if anything, it's the standard library. It uses the new natives from 1.29+

In general we only support the latest stable version. If you want to build with an older version you need to manually check out the pre1.29 branch and replace the common.j and blizzard.j in your project's _build folder with old variants from your game files. 

There is no easy legacy build at this point, sorry.

**Comment by HarounGY** [comment]
think you ！
I'll try.

**Comment by Frotty** [comment]
Any update on this?
