### ISSUE TITLE
Experience reward

### ISSUE THREAD

**Issue by HarounGY** [Frotty/Frentity#7]
when my hero kill  unit  create by UnitEntity, hero can not get experience.
Gold is ok!!!
i Already open PLAYER_STATE_GIVES_BOUNTY 
what shoud i do .  help me

**Comment by Frotty** [comment]
Frentity has nothing to do with experience given by units.
Does the unit give experience when not created via UnitEntity?

**Comment by HarounGY** [comment]
![GFZ%6K1F2 3 G4@1% $P3)A](https://user-images.githubusercontent.com/17424154/65232253-6c4ed000-db03-11e9-9186-031a339a39da.png)

Second sentence is ok

**Comment by Frotty** [comment]
> Second sentence is ok

What? You mean the second unit gives experience?

> Gold is ok!!!

Gold in this example is given via `onDeath`

**Comment by HarounGY** [comment]
no，player get 125 gold 25 come from unit ，100 come from addglod

**Comment by HarounGY** [comment]
the issue  caused by  “UnitApplyTimedLife”  ！

**Comment by Frotty** [comment]
So it's your code (or the one you copied), not Frentity.

**Comment by HarounGY** [comment]
yes， i copy the from “ForestDef”； I'm still learning wurstscript，thanks for you help。
